version: "3.8"

services:
  db:
    image: postgres:13
    env_file: ./OrdersAPI/.env
    ports:
      - "0.0.0.0:5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db_data:
